/**
 * reports.ts handler — fixed PDF download
 */
import { APIGatewayProxyHandler } from "aws-lambda";
import PDFDocument from "pdfkit";
import {
  getAllReports,
  getReportById,
  createReport,
  deleteReport,
  incrementDownloads,
} from "../services/reportsService";
import { getUserId } from "../utils/getUserId";
import {
  ok,
  notFound,
  badRequest,
  unauthorized,
  serverError,
  isAuthError,
  CSV_HEADERS,
  PDF_HEADERS,
} from "../utils/response";

export const getReports: APIGatewayProxyHandler = async (event) => {
  try {
    const userId = getUserId(event);
    return ok(await getAllReports(userId));
  } catch (err: any) {
    return isAuthError(err) ? unauthorized(err.message) : serverError();
  }
};

export const createReport_: APIGatewayProxyHandler = async (event) => {
  try {
    if (!event.body) return badRequest("Missing request body");
    const userId = getUserId(event);
    return ok(await createReport(userId, JSON.parse(event.body)));
  } catch (err: any) {
    return isAuthError(err) ? unauthorized(err.message) : serverError();
  }
};

export const filterReports: APIGatewayProxyHandler = async (event) => {
  try {
    const userId = getUserId(event);
    const { type, status } = event.queryStringParameters || {};
    let items = await getAllReports(userId);
    if (type) items = items.filter((r) => r.type === type);
    if (status) items = items.filter((r) => r.status === status);
    return ok(items);
  } catch (err: any) {
    return isAuthError(err) ? unauthorized(err.message) : serverError();
  }
};

export const exportReports: APIGatewayProxyHandler = async (event) => {
  try {
    const userId = getUserId(event);
    const items = await getAllReports(userId);
    const csv = [
      "title,generated,type,status,downloads,emissions,renewableEnergy,waterUsage,wasteRecycled",
      ...items.map((r) =>
        [
          r.title,
          r.generated,
          r.type,
          r.status,
          r.downloads,
          r.emissions,
          r.renewableEnergy,
          r.waterUsage,
          r.wasteRecycled,
        ]
          .map((v) => `"${String(v ?? "").replaceAll('"', '""')}"`)
          .join(","),
      ),
    ].join("\n");
    return { statusCode: 200, headers: CSV_HEADERS("reports.csv"), body: csv };
  } catch (err: any) {
    return isAuthError(err) ? unauthorized(err.message) : serverError();
  }
};

export const downloadReport: APIGatewayProxyHandler = async (event) => {
  try {
    const id = event.pathParameters?.id;
    if (!id) return badRequest("Missing id");

    const userId = getUserId(event);
    const report = await getReportById(id, userId);
    if (!report) return notFound("Report not found");

    const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
      const doc: PDFKit.PDFDocument = new (PDFDocument as any)({ margin: 50 });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text(report.title, { align: "center" });
      doc.moveDown(0.5);
      doc
        .fontSize(12)
        .font("Helvetica")
        .fillColor("#666666")
        .text(`Generated: ${new Date(report.generated).toLocaleDateString()}`, {
          align: "center",
        });
      doc.moveDown(2);
      doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor("#e5e7eb").stroke();
      doc.moveDown(1);

      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .fillColor("#111827")
        .text("Key Metrics");
      doc.moveDown(0.5);

      [
        [
          "Carbon Emissions",
          `${(report.emissions / 1000).toFixed(1)}K kg CO2e`,
        ],
        ["Renewable Energy", `${report.renewableEnergy}%`],
        ["Water Usage", `${(report.waterUsage / 1000).toFixed(1)}K liters`],
        ["Waste Recycled", `${report.wasteRecycled}%`],
      ].forEach(([label, value]) => {
        doc
          .fontSize(12)
          .font("Helvetica-Bold")
          .fillColor("#374151")
          .text(label, { continued: true });
        doc.font("Helvetica").fillColor("#6b7280").text(`  ${value}`);
        doc.moveDown(0.3);
      });

      doc.moveDown(1);
      doc
        .fontSize(10)
        .fillColor("#9ca3af")
        .text("Generated by SustainHub", { align: "center" });
      doc.end();
    });

    await incrementDownloads(id, userId).catch((e) =>
      console.warn("increment failed:", e),
    );

    return {
      statusCode: 200,
      headers: PDF_HEADERS(`${report.title}.pdf`),
      body: pdfBuffer.toString("base64"),
      isBase64Encoded: true,
    };
  } catch (err: any) {
    console.error("downloadReport error:", err);
    if (err.message === "Not found") return notFound();
    return isAuthError(err)
      ? unauthorized(err.message)
      : serverError(err.message);
  }
};

export const deleteReport_: APIGatewayProxyHandler = async (event) => {
  try {
    const id = event.pathParameters?.id;
    if (!id) return badRequest("Missing id");
    await deleteReport(id, getUserId(event));
    return ok({ message: "Report deleted" });
  } catch (err: any) {
    if (err.message === "Not found") return notFound();
    return isAuthError(err) ? unauthorized(err.message) : serverError();
  }
};

export {
  createReport_ as createReport,
  createReport_ as generateReport,
  deleteReport_ as deleteReport,
};
